version: '3.8'

services:
    iot-inspector-local:
        image: iot-inspector-local
        network_mode: "host"
        build:
            network: host
            context: iot-inspector-local/src
            dockerfile: Dockerfile

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db       
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3 
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    iot-traffic-lights:
        image: iot-traffic-lights
        restart: on-failure
        network_mode: "host"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mongo
            - iot-inspector-local
        build:
            network: host
            context: iot-traffic-lights
            dockerfile: Dockerfile
        environment:
            MONGOHQ_URL: mongodb://root:example@localhost:27017/iot-traffic-lights-dev?authSource=admin
            HUE_DOMAIN: http://192.168.1.57
            HUE_USER: fm2kbtRnqsraPJZfzHa9nmswHIJxI-tB3vMUGoG1
            HUE_LIGHT_ID: 14
            IOT_INSPECTOR_DOMAIN: http://localhost:46241